# Generated by Django 2.2 on 2021-01-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='cart',
        ),
        migrations.AddField(
            model_name='purchase',
            name='cart',
            field=models.ManyToManyField(to='shops.Product', verbose_name='Корзина'),
        ),
    ]
