# Generated by Django 2.2 on 2021-01-28 12:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_auto_20210127_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
